name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: publish

  deploy:
    needs: build
    runs-on: [self-hosted, windows]
    steps:
      - name: Download Published Files
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: ./app

      - name: Deploy to Remote IIS via WinRM
        run: |
          $securePassword = ConvertTo-SecureString 'Esoft@1234' -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential ( 'attendance\esoft', $securePassword)

          Invoke-Command -ComputerName '192.168.0.20' -ScriptBlock {
            param($sourcePath)
            Import-Module WebAdministration
            Stop-WebSite -Name "SimpleMvcApp"
            Remove-Item -Recurse -Force "C:\inetpub\wwwroot\Production\SimpleMvcApp\*" -ErrorAction SilentlyContinue
            Copy-Item -Path $sourcePath\* -Destination "C:\inetpub\wwwroot\Production\SimpleMvcApp\" -Recurse -Force
            Start-WebSite -Name "SimpleMvcApp"
          } -ArgumentList "$PWD\app" -Credential $cred     