name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: publish

  deploy:
    needs: build
    runs-on: [self-hosted, windows]
    env:
      REMOTE_USERNAME: ${{ secrets.REMOTE_USERNAME }}
      REMOTE_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
      REMOTE_SERVER_IP: ${{ secrets.REMOTE_SERVER_IP }}

    steps:
      - name: Download Published Artifact
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: ./app

      - name: Deploy to Remote IIS via WinRM
        shell: pwsh
        run: |
          $localPublishPath = Join-Path $PWD "app"
          $securePassword = ConvertTo-SecureString $env:REMOTE_PASSWORD -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential ($env:REMOTE_USERNAME, $securePassword)

          $session = New-PSSession -ComputerName $env:REMOTE_SERVER_IP -Credential $cred

          Invoke-Command -Session $session -ScriptBlock {
          $msg = "$(Get-Date) ✅ Remote script reached"
          Add-Content -Path "C:\Deploy\SimpleMvcApp\test.txt" -Value $msg
          }

